name: Build & Test

on:
  workflow_dispatch:
  # pull_request:
  #   types: [opened, reopened, synchronize]
  # push:
  #   branches:
  #   - main

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'
      - uses: actions/checkout@v3
      - name: iOS build and test
        run: |
          set -o pipefail
          xcodebuild test -project PokemonGuider.xcodeproj -testPlan PokemonGuider -scheme PokemonGuider -enableCodeCoverage YES -resultBundlePath './TestResult.xcresult' -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2' build test | xcpretty
      - name: Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          xcode: true
          xcode_archive_path: './TestResult.xcresult'
